global:
  scrape_interval: 15s  # How often to scrape targets by default

scrape_configs:
  - job_name: 'API'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'

    static_configs:
      - targets: ['api:8083']

  - job_name: 'otel-collector'
    scrape_interval: 5s
    metrics_path: '/metrics'

    static_configs:
      - targets: ['otel-collector:8888']
